### ISSUE TITLE
feat: add `codegen` script

### ISSUE THREAD

**Issue by d1y** [EdvaldoMartins/flutter_pub_dev#6]
But. I clone the repo
But it can't run, after looking at the `pubspec.yaml` file
I found that the script generation needs to be executed,
Like this

```sh
flutter pub run build_runner build --delete-conflicting-outputs
```

After running successfully :) 👍🏻 

I recommend adding this line in `readme.md` to generate the code command

**Comment by srnunio** [comment]
Thanks for the suggestion, I also saw your changes, very good mainly the Chinese language :)
