### ISSUE TITLE
feat: markdown support code syntax highlighting

### ISSUE THREAD

**Issue by d1y** [EdvaldoMartins/flutter_pub_dev#9]
This plugin looks good, can the author accept my PR?

https://github.com/asjqkkkk/markdown_widget

**Comment by srnunio** [comment]
I don't understand the question  🤔

**Comment by d1y** [comment]
I use [GitTouch](https://apps.apple.com/cn/app/gittouch/id1452042346),  But. The `markdown` render the syntax highlighting, the is cool, I would like to add support for this :)

> **Can you give you tg/tw id**, want to discuss with you

![IMG_AA0682548207-1](https://user-images.githubusercontent.com/45585937/162556390-f5571c31-d22d-4ee5-9864-db0faa5025c8.jpeg)

Thank you
